version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - 8000:80
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - api
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Europe/Paris 
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - api
volumes:
  my-db:
networks:
  api:
    external: true
    name: api_network